# Generated by Django 4.1.7 on 2023-02-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_intropost'),
    ]

    operations = [
        migrations.AddField(
            model_name='intropost',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
