# Generated by Django 4.1.7 on 2023-02-23 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag', to='blog.category'),
        ),
    ]
