# Generated by Django 4.1.7 on 2023-02-25 17:34

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='writter',
            field=models.CharField(max_length=100, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
