# Generated by Django 4.1.7 on 2023-03-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_writter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='writter',
        ),
    ]
