# Generated by Django 4.1.7 on 2023-08-09 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authors_comment',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
